### ISSUE TITLE
"EventType.NotificationResponse" isn't fired when the notification is opened while the app is in the background or foreground on Android 

### ISSUE THREAD

**Issue by EmanOmarOthman** [urbanairship/react-native-airship#398]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
```
"react-native": "0.64.2"
"urbanairship-hms-react-native": "12.0.0",
"urbanairship-react-native": "12.0.0",
``` 

### What are the versions of any relevant development tools you are using?
```
Android Studio v4.2.2
Visual studio code v1.63.2
Node.js v14.16.0
```

# Report

### What unexpected behavior are you seeing?
The `"EventType.NotificationResponse"` isn't fired when the notification is opened while the app is in the background or foreground on Android, it required that the first notification received by the app to be opened while the app is killed after that the listener is fired on all app states "Background, Foreground, The app is killed"

### What is the expected behavior?
The `"EventType.NotificationResponse"` should be fired when the notification is opened while the app is at any state

### What are the steps to reproduce the unexpected behavior?
1- just integrate with `"urbanairship-react-native": "12.0.0"`
2- add the listeners of UrbanAirship at the `componentDidMount` of the App.js

```
 componentDidMount () {
    UrbanAirship.setUserNotificationsEnabled(true)
    if (Platform.OS === 'ios') {
      UrbanAirship.setForegroundPresentationOptions({
        alert: true,
        sound: true,
        badge: true,
      })
    }

    UrbanAirship.addListener(EventType.NotificationResponse, (response) => {
      EventRegister.emit('onSetNotification', response)
    })

    UrbanAirship.addListener(EventType.Registration, (event) => {
      NativeModules.ReactNativeJsBridge.setAirshipChannelId(event.channelId)
    })

  }
```

3- open the app and keep it in the foreground 
4- send notification and open it
the `"EventType.NotificationResponse"` will not be fired and that is the issue, we need this listener to be fired from the first time to get the response and handle the complete scenario 

### Do you have logging for the issue?
No

**Comment by rlepinski** [comment]
You need to move adding your listener outside of `componentDidMount`, that will only be called on foreground.

**Comment by andrewleeheb** [comment]
In my case I tried using **EventType.InboxUpdated** and it doesn't get fired too.

Im putting it in the useEffect() whenever i launch the application

**Comment by rlepinski** [comment]
@andrewleeheb iOS the react context is bound during the normal app init process. On Android, it is bound during the activity lifecycle. The activity only launches on foreground. You will need to move the events outside of those component callbacks.

**Comment by amirmorcos1234** [comment]
Hello @rlepinski ,
What do you mean by outside componentDidMount ?

**Comment by rlepinski** [comment]
For the sample app, we do it in the root `index.js` file.
```
/* Copyright Airship and Contributors */
/**
 * @format
 */

import { AppRegistry } from 'react-native';
import App from './App';
import { name as appName } from './app.json';
import {
  EventType,
  UrbanAirship,
} from 'urbanairship-react-native'

import { AirshipChat } from 'urbanairship-chat-react-native'


AppRegistry.registerComponent(appName, () => App);

UrbanAirship.addListener(EventType.PushReceived, async (event) => {
  console.log("Push Received: " + JSON.stringify(event));
})

```

Your app will be loaded but the component methods will not be called until the app is in the foreground.

**Comment by andrewleeheb** [comment]
> 

Was trying to use the InboxUpdatedEvent to get the unread count whenever the app launched/running.

I've tried to put the whole event outside of the component but still it doesn't work as expected.

Did tried to update to plugin and android sdk version to the latest 13.2.0 and 16.3.0 respectively, but it got error after the build:-
![image](https://user-images.githubusercontent.com/99241182/153334213-de4058f7-5b71-4894-a04d-038c568c6216.png)

**Comment by EmanOmarOthman** [comment]
Hello @rlepinski, we tried to move adding the listeners to the `index.js` file, but it didn't work, the listener is still not fired on the foreground, it isn't clear to me what said in your comment

> You need to move adding your listener outside of `componentDidMount`, that will only be called on foreground.
https://github.com/urbanairship/react-native-module/issues/398#issuecomment-1031636000

the issue is that is the app isn't fired when the app is in the foreground, it is only fired if the app is killed and I send a notification then opened the notification

**Comment by rlepinski** [comment]
@EmanOmarOthman Could you post sample code how you are trying to listen for it?

**Comment by EmanOmarOthman** [comment]
@rlepinski 

```
import './App/Config/ReactotronConfig'
import { AppRegistry } from 'react-native'
import 'react-native-gesture-handler'
import App from './App/Containers/App'

AppRegistry.registerComponent('xxxxxxxxxxx', () => App)

UrbanAirship.setUserNotificationsEnabled(true)
if (Platform.OS === 'ios') {
  UrbanAirship.setForegroundPresentationOptions({
    alert: true,
    sound: true,
    badge: true,
  })
}

UrbanAirship.addListener(EventType.NotificationResponse, (response) => {
  EventRegister.emit('onSetNotification', response)
})

UrbanAirship.addListener(EventType.Registration, (event) => {
  NativeModules.ReactNativeJsBridge.setAirshipChannelId(event.channelId)
})
```

**Comment by rlepinski** [comment]
@EmanOmarOthman where are you listening for `onSetNotification` ?

**Comment by EmanOmarOthman** [comment]
@rlepinski  in the `componentDidMount` of `RootContainer.js`

**Comment by rlepinski** [comment]
@EmanOmarOthman I really sorry, I was reading this issues as push received not a notification response event. The notification response event is perfectly fine to listen for during componentDidMount.

The module queues up events if it doesn't have a listener and will dispatch them once your listener is connected. Could you try subscribing to the event on componentDidMount and unsubscribe during componentWillUnmount. Also could you add a log statement to make sure its not app code vs the listener? 

Ill try to reproduce using the right event... 😳

**Comment by Ulrico972** [comment]
I made the test of listening the notification response event and I confirm it's working well.
Like ryan said, you can listen for notification response event during componentDidMount. And as he recommended, could you add a log statement to make sure its not app code vs the listener ?

**Comment by trajkovvlatko** [comment]
Hi everyone! I went through the suggestion you provided here, listen for Airship events outside the React app, push a custom event from inside Airship's callback to some component inside the app. 

With a lot of struggles and very unsafe events sent back and forth that can easily go wrong, this makes the notifications work while the app is in the background.

I wonder, is there any plan to implement this whole process inside the Airship module and be able to listen to notification received inside a component without this odd workaround?

Thanks for your help!

**Comment by rlepinski** [comment]
@trajkovvlatko You can listen for push received in the app lifecycles but on Android you will not be notified of them until the app is opened. This is a react limitation. The react context is not setup until the activity is started. You can read more about headless-js here - https://reactnative.dev/docs/headless-js-android

**Comment by rlepinski** [comment]
@EmanOmarOthman Are you still having issue with this event? If not Ill close this issue
