### ISSUE TITLE
Feature Request: Generic NotificationStatus event

### ISSUE THREAD

**Issue by roryabraham** [urbanairship/react-native-airship#427]
# Preliminary Info

### What Airship dependencies are you using?

We're using urbanairship-react-native `^11.0.2`, but this feature does not yet exist on the main branch.

### What are the versions of any relevant development tools you are using?

n/a

# Feature Request
We are looking for a reliable way to keep track of which users have allowed push notifications for our app and which have not. We've investigated, and it seems like this library provides some of the features we need to do this. We can use [`getNotificationStatus`](https://github.com/urbanairship/react-native-module/blob/bc8f7c95150c03c23553c0248c103e3157bfeeda/urbanairship-react-native/js/UrbanAirship.ts#L855-L862) to get a [`NotificationStatus`](https://github.com/urbanairship/react-native-module/blob/bc8f7c95150c03c23553c0248c103e3157bfeeda/urbanairship-react-native/js/UrbanAirship.ts#L446-L476) object. This contains all the information we need to know if a user will receive push notifications:

- `airshipOptIn`
- `airshipEnabled`
- `systemEnabled`
- `ios.authorizedStatus`

However, the next task is keeping that information up-to-date. While there are a few potential workarounds we're aware of, I did notice that it's possible to set up a listener for the [`NotificationOptInStatus` event](https://github.com/urbanairship/react-native-module/blob/bc8f7c95150c03c23553c0248c103e3157bfeeda/urbanairship-react-native/js/UrbanAirship.ts#L73), which presumably is emitted whenever opt-in status changes.

We would love to see a generic `NotificationStatus` event, that's emitted whenever _any_ of the `NotificationStatus` fields change, including those listed above.

**Comment by roryabraham** [comment]
BTW, I don't really understand the difference between `airshipOptIn` and `airshipEnabled` – couldn't find anything in the docs.

**Comment by rlepinski** [comment]
- `airshipOptIn` is the channel opted in to receive a push from Airship. This can be false for a few reasons: device token missing, privacy manager push flag is disabled, system enabled is false, or push is disabled. When this is true you should be able to send a push to the device. 
- `airshipEnabled`: Flag probably is not needed and we should consider removing it if its causing confusion. Its just the `userPushNotificationsEnabled` flag that you can set directly on the SDK.
- `systemEnabled`:  If notifications are enabled at the system level for the app.


We could provide that event, but really the only one that you are not in control of is the `systemEnabled` and `ios.authorizedStatus. Assuming you enable user notifications on Airship and have the app configured properly the only thing that could change is if the user disables notifications from the system settings, which you would receive the current NotificationOptInStatus event.

**Comment by roryabraham** [comment]
Thanks @rlepinski!

> Assuming you enable user notifications on Airship and have the app configured properly the only thing that could change is if the user disables notifications from the system settings, which you would receive the current NotificationOptInStatus event.

Awesome! Does `NotificationOptInStatus` get emitted on iOS as well, or just Android?

**Comment by rlepinski** [comment]
On both, but they are slightly different. Android we track the enabled status in the system settings. I assume once Android 13 comes out it will be the notification permission but we are still looking into that. On iOS, you will receive that event if any of the authorized types changed, so it could be if all are disabled or if the user just modifies a single permission like removing badging.

**Comment by rlepinski** [comment]
Added in 16.x but changed the status object slightly - https://github.com/urbanairship/react-native-airship/blob/main/MIGRATION.md#notification-status

https://github.com/urbanairship/react-native-airship/blob/main/MIGRATION.md#notificationoptinstatusevent-replaced
