### ISSUE TITLE
getChannelId is always returning 

### ISSUE THREAD

**Issue by MaganAnkur** [urbanairship/react-native-airship#445]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
"urbanairship-react-native": "^14.4.1",

### What are the versions of any relevant development tools you are using?
"react": "17.0.2",
   "react-native": "0.66.4",

# Report

### What unexpected behavior are you seeing?
getChannelId is always returning 'undefined'despite doing `enbaleChannelCreation` and setting up `isChannelCreationDelayEnabled` to true

### What is the expected behavior?
getChannelId should return the channel id.

## Init Airship

`
 useEffect(() => {
   Notifications.initUrbanAirship();
 Notifications.enableAirshipNotification();
  }, []);
`
## Notifications.js

`
export class Notifications {
  static initUrbanAirship() {
    UrbanAirship.takeOff({
      default: {
        appSecret: Config.AIRSHIP_APP_SECRET,
        appKey: Config.AIRSHIP_APP_KEY,
      },
      site: 'us', // use "eu" for EU cloud projects
      urlAllowList: ['*'],
      android: {
        notificationConfig: {
          icon: 'driver_icon',
        },
      },
      isChannelCreationDelayEnabled: true,
    });
  }

  static enableAirshipNotification = () => {
    UrbanAirship.setUserNotificationsEnabled(true);
    UrbanAirship.enableChannelCreation();
  };
}

`

**Comment by rlepinski** [comment]
Could you set log level to verbose and see whats going on with the requests? Also, why are you setting `isChannelCreationDelayEnabled` and then immediately enabling it?
