### ISSUE TITLE
Push Notification Custom Sound

### ISSUE THREAD

**Issue by venukaaventude** [urbanairship/react-native-airship#488]
Want to change default notification sound in both ios and android and used the "sound" key in the REST API and send the exact same name of the sound file that attach in to resources but still play the default sound after the notification triggered.
 
Airship dependencies 
"urbanairship-react-native": "^12.0.0",
"react-native": "0.60.6",
"react": "16.8.6",

_In console it show like this when notification triggered_

**invokeCallbackAndReturnFlushedQueue@[native code]
2023-02-28 19:04:06.885490+0530 TFVTolka[5920:1449698] [D] +[UAAppIntegration userNotificationCenter:willPresentNotification:withCompletionHandler:] [Line 80] Notification center will present notification: <UNNotification: 0x281fd8480; source: se.tolkformedlingvast.tolkapp date: 2023-02-28 13:34:06 +0000, request: <UNNotificationRequest: 0x281fdbb40; identifier: BA5EC43A-19C1-47CE-B3BC-A0BC9341D80A, content: <UNNotificationContent: 0x15d309480; title: <redacted>, subtitle: (null), body: <redacted>, summaryArgument: (null), summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: <UNNotificationSound: 0x283b3aa70>, realert: 0, interruptionLevel: 1, relevanceScore: 0.00, filterCriteria: (null), trigger: <UNPushNotificationTrigger: 0x28123d2b0; contentAvailable: NO, mutableContent: NO>>, intents: (
)>
2023-02-28 19:04:06.886113+0530 TFVTolka[5920:1449698] [I] +[UAAppIntegration handleIncomingNotification:foregroundPresentation:completionHandler:] [Line 191] Received notification: {
    NotificationType = emergency;
    "_" = "b15bc4f1-40de-4489-b8a0-c650bbc945f4";
    aps =     {
        alert =         {
            body = "Tolk Push Message 26695";
            title = "Tolk Test - 26692";
        };
        sound = sound;
    };
    "com.urbanairship.metadata" = "eyJ2ZXJzaW9uX2lkIjoxLCJ0aW1lIjoxNjc3NTkxMjQ1OTU3LCJwdXNoX2lkIjoiOTA1OWQyMzAtYjc2Yy0xMWVkLThiNGMtMDI0MmE1NjJiNDE3In0=";
    externalnotificationidentifier = "C613E46A-18F6-4ADF-8C11-00EAD78008FA";
}**

<img width="1193" alt="Screenshot 2023-03-01 at 12 00 00" src="https://user-images.githubusercontent.com/116064318/222062766-60bddf4a-e838-421d-98c6-eef24ca7522f.png">
<img width="1193" alt="Screenshot 2023-03-01 at 12 00 36" src="https://user-images.githubusercontent.com/116064318/222062795-d02e6e5f-6706-4b9f-bce3-310c4e4d241f.png">

**Comment by rlepinski** [comment]
I think you need to send `sound.wav`. The OS is responsible for playing the sounds, not Airship, so you can follow docs provided by Apple - https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification

**Comment by venukaaventude** [comment]
@rlepinski this is working with ios but in androd still playing default device sound and try with latest android sdk version 32.
is there any thing i have do in code?
this is the location i placed my sound file
<img width="481" alt="Screenshot 2023-03-10 at 14 04 45" src="https://user-images.githubusercontent.com/116064318/224266338-bb64cf7f-1445-45b1-918e-ed0d3ef75318.png">

**Comment by rlepinski** [comment]
Ok, so for Android that sound rest api key is no longer usable since Android 8.0. Instead sound, vibrate, priority, etc.. are all controlled by a notification category/channel. 

Move your sound file to `res/raw/sound.wav`, then create a new file for defining channels in `res/xml/ua_custom_notification_channels.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <NotificationChannel
        id="some_channel_id"
        name="User facing name"
        description="User facing description"
        sound="sound"
        importance="3" />
</resources>
``` 

You can then specify the channel in the payload with:
```
    "notification" : { 
        "android": {
            "notification_channel": "some_channel_id",
             ...
```

Here is a screenshot of my project:
![Uploading Screenshot 2023-03-10 at 11.23.12 AM.png…]()

**Comment by venukaaventude** [comment]
@rlepinski thanks for your support. it's work now
