### ISSUE TITLE
Notification background color issue with Android

### ISSUE THREAD

**Issue by venukaaventude** [urbanairship/react-native-airship#497]
Want to change android notification icon background into white color and already change in **airshipconfig.properties** like this

```
# Notification customization
notificationIcon = ic_notification
notificationAccentColor = #ffffff
```
but when notification triggered it show in gray color

Airship dependencies
"urbanairship-react-native": "^12.0.0",
"react-native": "0.60.6",
"react": "16.8.6",

<img width="459" alt="Screenshot 2023-04-06 at 11 45 24" src="https://user-images.githubusercontent.com/116064318/230288037-4ebbfea6-1203-4cfd-860b-82d67ae9e22a.png">
<img width="641" alt="Screenshot 2023-04-06 at 11 55 26" src="https://user-images.githubusercontent.com/116064318/230289411-fa1ae11e-1841-44ee-b86b-24cf6d7a7b78.png">

**Comment by Ulrico972** [comment]
Hello,
I'm guessing your icon is colored. If that's the case, it's not an Airship issue but an Android one.
Starting from Android 4.4, the notification icons have to be monochrome, so with one color (white included) and transparent.

Tell us if that helps you
