### ISSUE TITLE
Missing `enableChannelCreation` in 15.x

### ISSUE THREAD

**Issue by leonchabbey** [urbanairship/react-native-airship#500]
As you mention in your [14.x to 15.x migration guide](https://github.com/urbanairship/react-native-airship/blob/main/MIGRATION.md), there should be a `Airship.channel.enableChannelCreation()` in 15.x which replaces `UrbanAirship.enableChannelCreation()`.

It seems like it's missing.

**Comment by rlepinski** [comment]
We can look into adding it back. However its basically been replaced by `privacyManager`. If you start the app will no enabled features the SDK will basically no-op until a feature is enabled. That includes channel creation.

**Comment by leonchabbey** [comment]
Alright it's fine then. I didn't realise it was replaced by the `privacyManager` and I've just seen now this: https://docs.airship.com/platform/mobile/data-collection/data-collection/#privacy-manager.

No need to put it back but maybe you could update the migration doc to not mention it anymore?

**Comment by rlepinski** [comment]
Updated the changelog. If you have any troubles with migrating over to privacy manager let me know
