### ISSUE TITLE
[Question] - Why iOS minimum version is 13 while iOS SDK support version 11 & react-native support version 12.4

### ISSUE THREAD

**Issue by gkueny** [urbanairship/react-native-airship#502]
I did not find any reason given in relation to the requirement iOS version 13.

I see that it was introduced by: https://github.com/urbanairship/react-native-airship/pull/482 

I am curious to know the reason.
Currently we are stuck in the upgrade to version 15.X because of this.
But knowing the reason for dropping the 12.X iOS version might give me some clues so that we drop this support as well.

**Comment by rlepinski** [comment]
Its so we can use modern swift concurrency features that is used by the proxy framework. In general we normally only support up to 3 major iOS versions, but we try to support as much as we can unless we have a valid reason to bump it. The swift concurrency is one of those core features that we need to be able to access going forward. 

In the next major SDK release in the next month or so, we will be moving to iOS 14+. This is to make it easier for us to develop swift UI views (our OOTB views), but also there is not a device out there that is stuck on iOS 13. I think a few devices are stuck on iOS 12, but not 13.
