### ISSUE TITLE
setAttribute apply returns [Error: Expected value for key: group]

### ISSUE THREAD

**Issue by AmineKenzup** [urbanairship/react-native-airship#504]
### What Airship dependencies are you using?
We're using @ua/react-native-airship 15.2.3
### What unexpected behavior are you seeing?

When I'm trying to apply contact attributes, I've got this error [Error: Expected value for key: group]
### What is the expected behavior?
It should update user's attributes 

### What are the steps to reproduce the unexpected behavior?
Try to set attributes for a user with contact or channel

### Do you have logging for the issue?
I've got only this error on catch  [Error: Expected value for key: group]

**Comment by rlepinski** [comment]
What OS is this happening on? Could you give me a code snippet to reproduce?

**Comment by rlepinski** [comment]
Looks like Android  - https://github.com/urbanairship/airship-mobile-framework-proxy/blob/main/android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/AttributeOperation.kt#L23

**Comment by AmineKenzup** [comment]
> Looks like Android - https://github.com/urbanairship/airship-mobile-framework-proxy/blob/main/android/airship-framework-proxy/src/main/java/com/urbanairship/android/framework/proxy/AttributeOperation.kt#L23

this is the code snippet:
`  await Airship.contact
        .editAttributes()
        .setAttribute('phone_number', phoneNumber)
        .apply();`

**Comment by rlepinski** [comment]
@AmineKenzup thanks! I see the issue, ill try to get a patch out today.

**Comment by rlepinski** [comment]
Fixed in 15.2.4

**Comment by rlepinski** [comment]
@AmineKenzup We found another issue but on iOS where they were silently failing. Please update to 15.2.5
