### ISSUE TITLE
PushNotifications not working on Android 13

### ISSUE THREAD

**Issue by berseck** [urbanairship/react-native-airship#507]
# Preliminary Info

### What Airship dependencies are you using?
"@ua/react-native-airship": "15.2.4",
"react": "18.2.0",
"react-native": "0.70.8",
"@react-native-firebase/analytics": "14.2.2",
"@react-native-firebase/app": "14.2.2",
"@react-native-firebase/crashlytics": "14.2.2",
"@react-native-firebase/messaging": "14.2.2",
    
Also tried to use the latest: 17.4.3

### What are the versions of any relevant development tools you are using?
buildToolsVersion = "31.0.0"
minSdkVersion = 29
compileSdkVersion = 31
targetSdkVersion = 31
supportLibVersion = "29.0.0"

# Report

### What unexpected behavior are you seeing?
I have the latest UA configured for Android and iOS
Both with the complete data configured all good.

I get the channelIDS I get that the notifications are activated in both.
But when I send any type of notification, either push notification or literally messages from the portal

iOS display the listener:
```
    Airship.addListener(EventType.PushReceived, (event) => {
      console.log('PushReceived:', JSON.stringify(event));
    });
```

But android never ever trigger that message.
I have tried to do release mode, dev mode... all modes I could possible try I tried on different Android 13 Devices.
I get no response at all.

Here is my configuration inside the app:
```
    Airship.takeOff({
      default: {
        appSecret: appSecret,
        appKey: appKey
      },
      site: 'us', // use "eu" for EU cloud projects
      urlAllowList: ['*'],
      urlAllowListScopeOpenUrl: ['*'],
      inProduction: true
    });

    Airship.push.setUserNotificationsEnabled(true);

    return Airship.push.isUserNotificationsEnabled().then(() => {
      return Airship.push.enableUserNotifications();
    });
```

Did I miss any type of configuration? I have followed the example given in the project.

I also tried to compile the project with version 33 and target as 33.
That enables push notification request from the app, that 31 doesn't. But still no go with any push notification information.

**Comment by rlepinski** [comment]
@berseck Its most likely your google services. If you look up your channel on the dashboard is it opted in? If it is, it means you have a token but it might be for the wrong app so check the config. If you do not have a token, then you are missing the google-serivces.json in your project

**Comment by berseck** [comment]
I do have a token there I can see my channel on the url:
https://go.airship.com/apps/your-project/contact_management/channel/my-channel-id/

It show there everything is set properly, this is why I'm not understanding why no push notifications are been sent.
I have same configuration but in a cordova app and it works as intended. (Off course the plugin is different... but it works)

I did downloaded the google-services.json directly from firebase portal and injected in the app folder etc all correct and I do have this:
```
apply plugin: "com.google.gms.google-services"
apply plugin: "com.google.firebase.crashlytics"
```

In my system as well installed as plugin for the firebase.

**Comment by rlepinski** [comment]
The other thing that might be happening is on Android you can only have a single push provider. If you have another push provider the messaging service will prevent our notifications from receiving in the SDK. When you build you app, could you provide me the merged manifest. It should be app/build/intermediates/merged_manifests/debug/AndroidManifest.xml. What I am looking for is entries for the firebase messaging service. This is the Airship one:
```
 <service
            android:name="com.urbanairship.push.fcm.AirshipFirebaseMessagingService"
            android:exported="false">
            <intent-filter android:priority="-1">
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```
Search for the `com.google.firebase.MESSAGING_EVENT` action name.

**Comment by berseck** [comment]
@rlepinski I don't see this added in the examples given in the docs also I don't see any of these in the code in the library for the manifest in this plugin files.

I will see if adding this manually will fix the issue, since I don't see also this been added to our project at all.

**Comment by berseck** [comment]
It was @react-native-firebase/messaging removing it when installing UA fixed the issue.

**Comment by rlepinski** [comment]
If you need both to work you can, but it requires a custom service. If you extend `io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService` and forward messages to Airship following - https://docs.airship.com/platform/mobile/setup/sdk/android/#extending-the-firebasemessagingservice, then register at a higher priority in the manifest it will enable both plugins.

**Comment by wilsolutions** [comment]
Interesting, I've ran into the same issue, would you have an example of a custom service?
Wouldn't this be helpful to be in the example project?

thank you

**Comment by rlepinski** [comment]
The custom service unfortunately depends on the plugin. I usually recommend extended the other plugins service and calling through to Airship due to not being easily able to forward messages to the other plugin.

For this one, its this service:
https://github.com/invertase/react-native-firebase/blob/main/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingService.java

If you look, they are not doing any blocking operations, so we can do an easier integration:
```
public class CustomFcmService extends ReactNativeFirebaseMessagingService {
    @Override
    public void onMessageReceived(@NonNull RemoteMessage message) {
        super.onMessageReceived(message);
        AirshipFirebaseIntegration.processMessageSync(getApplicationContext(), message);
    }

    @Override
    public void onNewToken(@NonNull String token) {
        super.onNewToken(token);
        AirshipFirebaseIntegration.processNewToken(getApplicationContext(), token);
    }
}
```

However this would work for the majority of services
```
public class CustomFcmService extends ReactNativeFirebaseMessagingService {
    @Override
    public void onMessageReceived(@NonNull RemoteMessage message) {
        Future<Void> future = AirshipFirebaseIntegration.processMessage(getApplicationContext(), message);
        super.onMessageReceived(message);
        try {
            future.get();
        } catch (Exception e) {
            Log.e("CustomFcmService", "Failed to wait for service", e);
        }
    }

    @Override
    public void onNewToken(@NonNull String token) {
        AirshipFirebaseIntegration.processNewToken(getApplicationContext(), token);
        super.onNewToken(token);
    }
}
```

Depending on the plugin, you have to change the `extends ReactNativeFirebaseMessagingService` part.

You can then register this in the  app's manifest, note the priority. It needs to be highest one in the manifest:
```
        <service
            android:name="com.example.CustomFcmService"
            android:exported="false">
            <intent-filter android:priority="100">
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

The other option is if you don't care to use the messaging feature of a plugin, but it offers something else, you can just remove the entry using using [manifest merging](https://developer.android.com/studio/build/manifest-merge), again this depends on what entry you are trying to remove:

```
 <service
        tools:node="remove"
        android:name="io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService"
        android:exported="false" >
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
</service>
```

I agree this would be nice to have somewhere to reference.

**Comment by berseck** [comment]
Thanks for the examples!

I went to the easy way and patched the firebase-messaging adding -2 as priority
```
--- a/node_modules/@react-native-firebase/messaging/android/src/main/AndroidManifest.xml
+++ b/node_modules/@react-native-firebase/messaging/android/src/main/AndroidManifest.xml
@@ -10,7 +10,7 @@
     <service android:name=".ReactNativeFirebaseMessagingHeadlessService" />
     <service android:name=".ReactNativeFirebaseMessagingService"
              android:exported="false">
-      <intent-filter>
+      <intent-filter android:priority="-2">
         <action android:name="com.google.firebase.MESSAGING_EVENT"/>
       </intent-filter>
     </service>
```

I will leave this here as reference if someone else needs this.

But I agree I need to work this via merge or maybe in a override class same as you explained.
But with this simple patch I was able to get things running as intended without many files changes and possible other issues that could pop up from this.

**Comment by zuhasohail18** [comment]
@rlepinski I have two push providers right now. Following are there details.
        <service
            android:name="com.google.firebase.messaging.FirebaseMessagingService"
            android:directBootAware="true"
            android:exported="false" >
            <intent-filter android:priority="-500" >
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <service
            android:name="com.urbanairship.push.fcm.AirshipFirebaseMessagingService"
            android:exported="false" >
            <intent-filter android:priority="-1" >
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

I never added the "com.google.firebase.messaging.FirebaseMessagingService" in app. It just got added by default when I integrated urbanairship. Now I'm unable to receive notifications on android. I tried removing provider but that file in merged_manifests gets overwritten everytime I build the project. 
@berseck Could you please help me understand how you removed that provider.

**Comment by zuhasohail18** [comment]
Whenever i set the priority, the file in android/app/build/intermediates/merged_manifests/debug/AndroidManifest.xml gets overwritten upon building the app. 
Currently in my project "io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService" and "com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService" have no priority set (0 by default), "com.google.firebase.messaging.FirebaseMessagingService" has priority = -500 and "com.urbanairship.push.fcm.AirshipFirebaseMessagingService" has priority = -1. 
I tried to change urbanship's priority to 100 but it reverted back to -1

**Comment by zuhasohail18** [comment]
I am trying to configure airship following way. Please tell me if i'm missing something. It is to be noted that I have same setup and notifications in my iOS device are working fine. In case of android, Channel Id also gets registered which I can see on Airship dashboard. 
Interestingly when I send push notification, my notification is received in messaging().setBackgroundMessageHandler() but doesn't appear on screen.

Following steps are used to configure airship in my react native app.

1. On app launch I initialise airship by calling takeOff method in App.tsx
 UrbanAirship.takeOff({
        default: {
            appSecret: env.AIRSHIP_APP_SECRET_LIVE,
            appKey: env.AIRSHIP_APP_KEY_LIVE
        },
        site: "us",
        urlAllowList: ["*"],
        android: {
          notificationConfig: {
              icon: "ic_notification",
              accentColor: "#00ff00",
          }
      }
      })

2. Once user logs in UrbanAirship.setUserNotificationsEnabled(true) is called.

3. For android, I also added xml folder in android/app/src/main. ua_custom_notification_channels.xml was placed inside xml folder.
Its content is given below.
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <NotificationChannel
        id="com.cch.intellify"
        name="IntelliShift"
        description="Notification channel"
        importance="3" />
</resources>
