### ISSUE TITLE
Push successfully received on Android, but not displaying as a "heads-up" banner

### ISSUE THREAD

**Issue by dkulakov** [urbanairship/react-native-airship#511]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

`"@ua/react-native-airship": "15.2.5"`

### What are the versions of any relevant development tools you are using?

`"react-native": "0.70.6"`
`"@react-native-firebase/messaging": "17.1.0"`
`"react-native-onesignal": "4.5.0"`

```
buildToolsVersion = "33.0.0"
minSdkVersion = 23
compileSdkVersion = 33
targetSdkVersion = 33
```

I use workaround from the [issue](https://github.com/urbanairship/react-native-airship/issues/507)

```
public class CustomFcmService extends ReactNativeFirebaseMessagingService {
  @Override
  public void onMessageReceived(@NonNull RemoteMessage message) {
      super.onMessageReceived(message);
      AirshipFirebaseIntegration.processMessageSync(getApplicationContext(), message);
  }

  @Override
  public void onNewToken(@NonNull String token) {
      super.onNewToken(token);
      AirshipFirebaseIntegration.processNewToken(getApplicationContext(), token);
  }
}

<service android:name=".CustomFcmService" android:exported="false">
  <intent-filter android:priority="100">
    <action android:name="com.google.firebase.MESSAGING_EVENT" />
  </intent-filter>
</service>
```

# Report

### What unexpected behavior are you seeing?

Push notifications do not appear on top of the app, only in the notification center

### What is the expected behavior?

Push notifications should appear on top of the app and in the notification center

**Comment by dkulakov** [comment]
`app/build/intermediates/merged_manifests/debug/AndroidManifest.xml`

```
<service
    android:name="com.eph.superapp.CustomFcmService"
    android:exported="false" >
    <intent-filter android:priority="100" >
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>


<service
    android:name="io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService"
    android:exported="false" >
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>

<service
    android:name="com.onesignal.HmsMessageServiceOneSignal"
    android:exported="false" >
    <intent-filter>
        <action android:name="com.huawei.push.action.MESSAGING_EVENT" />
    </intent-filter>
</service>


<service
    android:name="com.urbanairship.push.fcm.AirshipFirebaseMessagingService"
    android:exported="false" >
    <intent-filter android:priority="-1" >
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>

<service
    android:name="com.google.firebase.messaging.FirebaseMessagingService"
    android:directBootAware="true"
    android:exported="false" >
    <intent-filter android:priority="-500" >
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
```

**Comment by dkulakov** [comment]
I've checked push notifications on android on [the example app](https://github.com/urbanairship/react-native-airship/tree/main/example) and I have the same behaviour, so should I additionally use the library `react-native-push-notification` for displaying notifications?

**Comment by rlepinski** [comment]
@dkulakov I would not route notifications through yet another plugin you can do it with Airship it just requires some setup. On Android notification behave based on the notification category/channel settings when you post them - 
https://developer.android.com/develop/ui/views/notifications/channels

You can provide an xml file in the app's resources and Airship will create those channels for you - https://docs.airship.com/platform/mobile/push/advanced/react-native/#adding-custom-notification-channels-android

Once you do that, you can specify the default channel ID in the android settings for takeOff, or per push. This is a similar issue: https://github.com/urbanairship/react-native-airship/issues/488

**Comment by dkulakov** [comment]
@rlepinski thanks, this solution works well!
