### ISSUE TITLE
Live Activity support

### ISSUE THREAD

**Issue by gkueny** [urbanairship/react-native-airship#517]
# Preliminary Info

### What Airship dependencies are you using?

`15.3.0`

# Report

Is it planned to support https://docs.airship.com/platform/mobile/ios-live-activities/ & https://docs.airship.com/platform/mobile/android-live-updates/ in `react-native-airship` ?

**Comment by rlepinski** [comment]
I am not sure how to support it through the plugin without some native API calls based on the APIs apple exposes. I believe you will have to implement the live activity natively using swiftUI. Once you get that working, we can work together to integrate it into Airship to handle the restore calls and figure out a way to start a live activity and track it.  We can probably take advantage of the Airship's actions framework to start/end/update a live activity so you do not have to expose and maintain a plugin to do that for you.

**Comment by gkueny** [comment]
> I believe you will have to implement the live activity natively using swiftUI

Yes indeed. 

Currently, we've implemented a `LiveActivity` natively with SwiftUi and we use an in-house module to link it with react-native code.

However, since we'd like this `LiveActivity` to be updated regularly without the app being in the foreground, we'd like to use airship notifications.

However, according to the docs (https://docs.airship.com/platform/mobile/ios-live-activities/), we'll need to call the following native methods:

```swift
Airship.channel.restoreLiveActivityTracking { restorer in
    await restorer.restore(
        forType: Activity<MyLiveActivityAttributes>.self
    )
}
```

& 

```swift
let activity = try Activity.request(
    attributes: attributes,
    contentState: state,
    pushType: .token
)

Airship.channel.trackLiveActivity(
    activity,
    name: "order-1234"
)
```

I wonder how these two actions could be performed via the `react-native-airship` module.

Is this even possible? 
I'm afraid we'd have to use specific native code.

**Comment by rlepinski** [comment]
`react-native-airship` is built on top the native SDK. You should be able to make calls to the SDK natively. You just need to import AirshipKit. 

Do you already have a way of starting a live activity from the react context? What is your app delegate written in, obj-c or swift? I can throw together an example on the restore call once i get that info

**Comment by rlepinski** [comment]
Assuming you are on objc for the app delegate, add this file to your project:

```
import Foundation
import AirshipKit


@objc
public class AirshipExtender: NSObject {

  fileprivate static let shared: AirshipExtender = AirshipExtender()


  @objc
  @MainActor
  public class func setup() {
    if (Airship.isFlying) {
      self.shared.airshipReady()
    } else {
      NotificationCenter.default.addObserver(forName: Airship.airshipReadyNotification, object: nil, queue: nil) { _ in
        Task { @MainActor in
          self.shared.airshipReady()
        }
      }
    }
  }

  @MainActor
  private func airshipReady() {
    // Make restore call here
  }
}
```

Then in AppDelegate.m, import the file using the `#import "<MODULE_NAME>-Swift.h" `, for me it was `#import "AirshipExample-Swift.h"`

Then update `application:didFinishLaunchingWithOptions:` to call through to the extender.

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [AirshipExtender setup];

  self.moduleName = @"AirshipExample";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

That will give you a swift hook to modify Airship when its ready regardless of how you call takeOff. I put a comment on a place holder for the restore call. 

Once you give me more info on how you start a LA i can give more examples

**Comment by gkueny** [comment]
> Do you already have a way of starting a live activity from the react context? 

Yeah, I already be able to start a Live activity 

> What is your app delegate written in, obj-c or swift? I can throw together an example on the restore call once i get that info
Obj-c 

> Assuming you are on objc for the app delegate, add this file to your project:

Thanks you for the example 🚀 , I will try this

Many thanks !
I assume you can close this issue

**Comment by rlepinski** [comment]
Woot, let me know if you need any more help!
