### ISSUE TITLE
Could not resolve com.urbanairship.android:urbanairship-hms:7.0.2.

### ISSUE THREAD

**Issue by MahmoudMedhat0** [urbanairship/react-native-airship#519]
# Preliminary Info

### What Airship dependencies are you using?

React-Native 70.7
@ua/react-native-airship 16.0.0

### What are the versions of any relevant development tools you are using?

Android Studio Electric Eel | 2022.1.1 Patch 2

# Report

### What unexpected behavior are you seeing?

when i run android i get this error `Could not resolve com.urbanairship.android:urbanairship-hms:7.0.2.`

### What is the expected behavior?

app build successfully as before 

### What are the steps to reproduce the unexpected behavior?

N.A

### Do you have logging for the issue?

N.A

**Comment by MahmoudMedhat0** [comment]
<img width="679" alt="Screenshot 2023-07-06 at 5 10 14 PM" src="https://github.com/urbanairship/react-native-airship/assets/89934348/be5afd56-de10-43c3-8da3-aac665b424f2">
i think you need change `Airship_airshipVersion` to `17.0.2` instead of `7.0.2`

**Comment by rlepinski** [comment]
Fixed in 16.0.1
