### ISSUE TITLE
Airship Message center is not working for android

### ISSUE THREAD

**Issue by AmineKenzup** [urbanairship/react-native-airship#525]
# Preliminary Info

### What Airship dependencies are you using?
@ua/react-native-airship: 16.0.1

# Report

### What unexpected behavior are you seeing?
I cannot see the message center inbox only, also message center OOTB UI

### What is the expected behavior?
I should see the messages and display the OOTB UI 

### What are the steps to reproduce the unexpected behavior?
1- send a message center notification
2- open the app 
3- nothing happens and the inbox is empty

**Comment by rlepinski** [comment]
Could you provide more details on whats going on?

> I cannot see the message center inbox only, also message center OOTB UI

Does the OOTB message center display for you? Just not showing any messages?

How are you sending a message center message? Does this work on iOS?

**Comment by AmineKenzup** [comment]
> Could you provide more details on whats going on?
> 
> > I cannot see the message center inbox only, also message center OOTB UI
> 
> Does the OOTB message center display for you? Just not showing any messages?
> 
> How are you sending a message center message? Does this work on iOS?

on iOS OOTB message center is displayed, also I can see the inbox messages for the same account, but when I switch to Android I cannot see them the inbox returns an empty array and the OOTB message is not shown

**Comment by rlepinski** [comment]
Could you enable verbose logging and share those logs with me for an Android session where you recieve the push , open it, and have nothing happen? https://docs.airship.com/platform/mobile/logging/?groupid=react-native

You can email the logs at ryan.lepinski@airship.com

**Comment by AmineKenzup** [comment]
> ryan.lepinski@airship.com

I've sent you the logs

**Comment by AmineKenzup** [comment]
After checking the verbose logs: I've found this warning
` W  Unable to show Message Center. FEATURE_MESSAGE_CENTER is not enabled in PrivacyManager.
`
The missing puzzle was, we need to enable features from privacy manager 
` await Airship.privacyManager.enableFeatures(FEATURES_ALL);`

**Comment by rlepinski** [comment]
🎉
