### ISSUE TITLE
Crashes on iOS with KERN_INVALID_ADDRESS, KERN_PROTECTION_FAILURE. v16.0.0

### ISSUE THREAD

**Issue by RayKay91** [urbanairship/react-native-airship#531]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

@ua/react-native-airship 16.0.0

### What are the versions of any relevant development tools you are using?

VSCode, Yarn

# Report

Hello, we're seeing a spike in the number of crashes with the following details. The sudden spike in crashes coincides with the app release containing version 16 of react-native-airship. It seems to have returned to normal levels, but it would be good to gain some insight as to why this occurred. 🙏 

### What unexpected behavior are you seeing?

High level of crashes on iOS with KERN_INVALID_ADDRESS and KERN_PROTECTION_FAILURE coming from the `ActionRunner.swift` class.

### What is the expected behavior?

No crashes.

### What are the steps to reproduce the unexpected behavior?

Unsure as the issue was noticed recently.

### Do you have logging for the issue?

```
Crashed: com.apple.root.user-initiated-qos.cooperative
0  libswiftCore.dylib             0x402cc4 swift_unknownObjectRelease + 20
1  Fabric                         0xc4970 specialized static ActionRunner.run(_:entry:value:situation:metadata:completionHandler:) + 223 (ActionRunner.swift:223)
2  Fabric                         0xc4be0 specialized static ActionRunner.run(_:value:situation:metadata:completionHandler:) + 84 (ActionRunner.swift:84)
3  Fabric                         0x86b4 specialized AirshipActionRunner.runAction(_:value:) + 60 (AirshipActionProxy.swift:60)
4  libswift_Concurrency.dylib     0x41948 swift::runJobInEstablishedExecutorContext(swift::Job*) + 416
5  libswift_Concurrency.dylib     0x42868 swift_job_runImpl(swift::Job*, swift::ExecutorRef) + 72
6  libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
7  libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
8  libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
9  libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

**Comment by rlepinski** [comment]
That is weird, I have seen crash spikes due to updates on Android but not iOS.

Are you running actions anywhere? Could you share your code?
