### ISSUE TITLE
How to create App Screens with Expo-Router?

### ISSUE THREAD

**Issue by idrakimuhamad** [urbanairship/react-native-airship#539]
Hi. I'm using Airship with Expo-Router, and trying to create the app-screens in the Airship portal. As i'm using expo-router, I'm having difficulty to grab the "uniqueID" or the screen name, as expo-router seems to predefined the screen name based on the files created.

Expo-router
https://docs.expo.dev/router/introduction/

Airship's app screen
https://docs.airship.com/guides/messaging/user-guide/in-app-experiences/configuration/app-screens/#adding-an-app-screen-to-your-project

Do you have any guide to this use case?

**Comment by rlepinski** [comment]
@idrakimuhamad Sorry about missing this issue before it must of been lost in the holiday time off shuffle. Did you actually get it resolved or did you just give up on us?

**Comment by idrakimuhamad** [comment]
> @idrakimuhamad Sorry about missing this issue before it must of been lost in the holiday time off shuffle. Did you actually get it resolved or did you just give up on us?

😂


I've actually contacted your support team about this and they mentioned that I must call the analytics module with the screen name for this to work. Is that correct?

**Comment by rlepinski** [comment]
Yeah, you need to manually call through to Airship since we do not want to make any assumptions on the screen being tracked since apps can be built differently. https://docs.airship.com/platform/mobile/analytics/?groupid=react-native#screen-tracking

```
Airship.analytics.trackScreen("MainScreen");
```

**Comment by idrakimuhamad** [comment]
Great. I will try it on then. Thanks!
