### ISSUE TITLE
Incorrect type definition on `listIconUrl` 

### ISSUE THREAD

**Issue by Peter-ChengTszTung** [urbanairship/react-native-airship#553]
Expecting `listIconUrl?: string;` instead of `listIconUrl: string;`

https://github.com/urbanairship/react-native-airship/blob/218bfe9a9e7b6935b2589e577262daf641874442/src/types.ts#L562-L567

**Comment by crow** [comment]
Good catch. Thanks!

**Comment by crow** [comment]
Have the change [here](https://github.com/urbanairship/react-native-airship/pull/554) - will include in the next release after coming through the rest of the typescript definitions and testing. Thanks again.
