### ISSUE TITLE
AirshipFrameworkProxy.AirshipProxyError on ios with expo 

### ISSUE THREAD

**Issue by henribruvier** [urbanairship/react-native-airship#562]
# Preliminary Info

### What Airship dependencies are you using?
`"@ua/react-native-airship": "^18.0.0",`
`"airship-expo-plugin": "^1.1.0",`

### What are the versions of any relevant development tools you are using?
`    "expo": "~50.0.17",
`

# Report

### What unexpected behavior are you seeing?
Push notifications no longer work on ios (not tested on android)
I tried to downgrade to the previous version but I get another error: [500] Takeoff not called.

### Do you have logging for the issue?
`The operation couldn’t be completed. (AirshipFrameworkProxy.AirshipProxyError error 1.)`

**Comment by rlepinski** [comment]
Is there any verbose logs or anything more than the error you have above? What Xcode version are you on?

**Comment by henribruvier** [comment]
I found the problem. I had to call the Airship.push.setUserNotificationsEnabled function after the takeOff function had succeeded. This was not the case in my implemenatation.
