### ISSUE TITLE
AirshipCore.UARemoteDataMapping errors after upgrading to v18.0.0

### ISSUE THREAD

**Issue by robwalkerco** [urbanairship/react-native-airship#563]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

```
"@ua/react-native-airship": "^18.0.0",
"airship-expo-plugin": "^1.1.0",
```

### What are the versions of any relevant development tools you are using?

# Report

### What unexpected behavior are you seeing?

After upgrading from `17.3.0` to `18.0.0`, there are a number of errors coming from Airship in the iOS Console, and these errors appear to prevent Push Notification and Live activity updates from being received.

`error: 	NSUnderlyingException : Couldn't create mapping policy for class named (AirshipCore.UARemoteDataMapping)`

`error: URL: file:///var/mobile/Containers/Data/Application/86FE60AF-43A5-4CBD-8B4C-95244E2501A2/Library/com.urbanairship.no-backup/RemoteData-f33alpf6RmmCuiBjpGAymQ.sqlite`

`error: 	NSUnderlyingException : Couldn't create mapping policy for class named (AirshipCore.UARemoteDataMapping)`

`[<private>] AirshipKit/UACoreData.swift createSqlStore(storeName:) [Line 433] <private>`

`[<private>] AirshipKit/RemoteDataProvider.swift payloads(types:) [Line 73] <private>`

If I uninstall the app, and then build and install using version `18.0.0`, then there are no errors, and everything works as expected, so it appears to only affect apps where the Airship version is upgraded.

This issue may be related in some way to https://github.com/urbanairship/ios-library/issues/391

### What is the expected behavior?
After upgrading, there would be no errors, and Live Activities and Push Notifications would continue to work

### What are the steps to reproduce the unexpected behavior?
 - Using `17.3.0` build, install and launch an app
 - Update the `react-native-airship` version to `18.0.0`
 - Build, install and launsh the app
 - Observe the errors from Airship in the iOS Console.

### Do you have logging for the issue?

Screenshot showing all the errors (error messages are included in the report above)
![Screenshot 2024-04-29 at 12 17 01](https://github.com/urbanairship/react-native-airship/assets/6524830/0d24b613-8f04-43b9-8cb3-a208145cd685)

**Comment by rlepinski** [comment]
Thanks for the report. This is a pod issue that we will figure out ASAP.

AirshipCore is common on SPM, xcframeworks, cathage, etc... but when using pods it bundles everything into a single `AirshipKit` framework.

**Comment by rlepinski** [comment]
We have a fix in the native sdk that is going out soon, then we will update the proxy and react-native

**Comment by robwalkerco** [comment]
Amazing. Thanks for the update

**Comment by rlepinski** [comment]
Out in 18.0.1
