### ISSUE TITLE
Creating local notification

### ISSUE THREAD

**Issue by idrakimuhamad** [urbanairship/react-native-airship#568]
Is it possible to create a local notification, which we can initiate within the app?

Like notifee:

https://notifee.app/react-native/docs/displaying-a-notification#notification-title--body

Or expo:

https://docs.expo.dev/versions/latest/sdk/notifications/#schedulenotificationasyncrequest

**Comment by rlepinski** [comment]
Nope, you need to use a different plugin for that. We only deal with remote notifications
