### ISSUE TITLE
`setForegroundDisplayPredicate` doesn't show the notification on foreground

### ISSUE THREAD

**Issue by idrakimuhamad** [urbanairship/react-native-airship#580]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

```
"@ua/react-native-airship": "^19.1.0"
```

# Report

### What unexpected behavior are you seeing?

When setting `setForegroundDisplayPredicate` predicate as true, it is not showing the incoming notification while the app is on foreground.

### What is the expected behavior?
I'm expecting that I would see or get the notification in the notification tray and sound

### What are the steps to reproduce the unexpected behavior?

```ts
Airship.push.android.setForegroundDisplayPredicate(
    () => Promise.resolve(true)
)
```

Is this expected or maybe I'm missing anything? Or does the notification send require some specific configuration for this to work?

**Comment by rlepinski** [comment]
It should default to displaying in the foreground. How are you sending the push? Do you have logs you can share?

**Comment by idrakimuhamad** [comment]
> It should default to displaying in the foreground. How are you sending the push? Do you have logs you can share?

The push are send from our backend. I think this the log looked like this.

![image](https://github.com/user-attachments/assets/38bd18dc-9d1f-4da4-86e4-7c56b563b637)

What confuses me is that I can see that the push send from the airship console are showing on foreground but not for the one from our backend.

**Comment by rlepinski** [comment]
You are sending this on Android `com.urbanairship.foreground_display: false`, try without that

**Comment by idrakimuhamad** [comment]
Ahh I see. I think they did this on purpose for the current app since they already have in app toast shown on foreground. I will need to adapt to this then and work with other means.

Anyway, does it mean that iOS will also behave this way?

**Comment by rlepinski** [comment]
On iOS, we dont look for that key, so its not needed. The default behavior is to not display on foreground. We have a similar method though that you can assign the foreground presentation options per notification to control this.https://docs.airship.com/reference/libraries/react-native/latest/classes/AirshipPushIOS.html#setForegroundPresentationOptionsCallback

**Comment by idrakimuhamad** [comment]
Ok so for iOS even the payload com.urbanairship.foreground_display: false is there, it will not looked at it. As such, if I use the setForegroundPresentationOptionsCallback to show the notification on foreground, it supposed to present the notification. Correct?

I just wanna confirm this cause since I can't change (yet) what backend send, so I need to use other library to show the notification. If this payload only affecting android, i will only handle this for Android and let iOS uses the SDK's API

**Comment by rlepinski** [comment]
> Ok so for iOS even the payload com.urbanairship.foreground_display: false is there, it will not looked at it. As such, if I use the setForegroundPresentationOptionsCallback to show the notification on foreground, it supposed to present the notification. Correct?

Correct, have full control at receive time


> I just wanna confirm this cause since I can't change (yet) what backend send, so I need to use other library to show the notification. If this payload only affecting android, i will only handle this for Android and let iOS uses the SDK's API

The level of effort to do that vs remote the key seems pretty high to me. Not to mention you will break some Airship features doing it that way:
- Any actions
- Reporting
- etc..

If you really cant just remove that key from your backend, I would recommend just scrubbing the key at receive time before Airship processes it. You can do that with registering your own FCM service:
```
package com.urbanairship.reactnative;

import android.os.Bundle;

import androidx.annotation.NonNull;

import com.google.firebase.messaging.RemoteMessage;
import com.urbanairship.push.fcm.AirshipFirebaseMessagingService;

public class FirebaseMessagingService extends AirshipFirebaseMessagingService {
    @Override
    public void onMessageReceived(@NonNull RemoteMessage message) {
        super.onMessageReceived(message);

        if (message.getData().containsKey("com.urbanairship.foreground_display")) {
            Bundle bundle = message.toIntent().getExtras();
            bundle.remove("com.urbanairship.foreground_display");
            RemoteMessage modified = new RemoteMessage(bundle);
            super.onMessageReceived(modified);
        } else {
            super.onMessageReceived(message);
        }
    }
}
```

Then register it in the manifest in the application entry:
```
        <service
            android:name=".FirebaseMessagingService"
            android:exported="false">
            <intent-filter android:priority="100">
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

**Comment by idrakimuhamad** [comment]
Yeah, because we currently shared the same backend with two different apps, with same purpose. However, the current app already handle foreground notifications with in app toast, while our new app we intend to just show the native notifications HUD when on foreground.

I can try that service workaround, that looks promising.

Also, on side note related to foreground, I've tried the iOS's setForegroundPresentationOptions, however i'm unable to get/see the notification. The push i sent are through the airship portal, and i'm able to receive it if the app is in background. I've actually filed a support request from the portal yesterday.

**Comment by rlepinski** [comment]
Its most likely being overridden by either your app delegate or some other plugin. Could you look for the usage of this:
```
-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
```

in your app delegate, or share it? If you are not implementing that, could you provide a list of the plugins you are using?

**Comment by idrakimuhamad** [comment]
I didn't have such usage in my app delegate, but that reminds me that I am using Notifee to create local notifications. I have looked into its code base, and they have that usage in their code.

I will try to remove it and see if that does the trick. If it does, I will try the workaround you provided for Android. That way, I wouldn't need to use Notifee anymore.

**Comment by rlepinski** [comment]
I think its Notifee that will cause the callback on iOS to not work - https://github.com/invertase/notifee/blob/main/ios/NotifeeCore/NotifeeCore%2BUNUserNotificationCenter.m#L99

**Comment by idrakimuhamad** [comment]
I can confirm removing notifee solved it for iOS. 

For Android, I've tried scrubbing the notification payload using the FCM service more or less like what suggested, however, it still doesn't seem to working out. I can still see the `com.urbanairship.foreground_display` inside the push received listener. For reference, I did it as below.

```
override fun onMessageReceived(message: RemoteMessage) {
        super.onMessageReceived(message)

        println("FirebaseMessagingService\n")
        println("Message: ${message.data}")

        // Create a mutable map from the original data
        val mutableData = message.data.toMutableMap()

        // Remove the undesired attribute
        mutableData.remove("com.urbanairship.foreground_display")

        // Log the modified message
        println("Modified Message: $mutableData")

        // Pass the modified data to the superclass
        super.onMessageReceived(RemoteMessage.Builder(message.from!!)
            .setMessageId(message.messageId!!)
            .setData(mutableData)
            .build())
```

I tried the sample you gave too with same results.

**Comment by idrakimuhamad** [comment]
I got it now. I need to remove the call to the superclass method in the beginning, and only call it once the message is updated.

Thanks @rlepinski !

**Comment by rlepinski** [comment]
Yep, i see I made that mistake in my example, sorry for that! Glad you got it figured out
