### ISSUE TITLE
>: ua_react-native-airship:compileDebugKotlin

### ISSUE THREAD

**Issue by sudesh-kumar-cse** [urbanairship/react-native-airship#587]
Getting ua_react-native-airship:compileDebugKotlin Issue
![image](https://github.com/user-attachments/assets/fd985677-5df1-45f7-9cb3-97d95bc30710)

and channel id not generating always getting null in android and undefined in iOS

**Comment by rlepinski** [comment]
Channel ID is not available right away, it requires a network request to generate. You can listen for when the channel is created with the  `ChannelCreated` event. 

I think the other issue you have is due to a few files missing for the old architecture. Looking into it.

**Comment by sudesh-kumar-cse** [comment]
> Channel ID is not available right away, it requires a network request to generate. You can listen for when the channel is created with the `ChannelCreated` event.
> 
> I think the other issue you have is due to a few files missing for the old architecture. Looking into it.


Thank you for your quick response its working if remove version range operator (^) and downgrade the library
"@ua/react-native-airship": "19.1.0",

**Comment by DigenPrimeApps** [comment]
Same error when generating build with version 19.3.0, but works fine with previous versions

**Comment by rlepinski** [comment]
Fixed in 19.3.1

**Comment by sudesh-kumar-cse** [comment]
> Fixed in 19.3.1

Thank you for your quick response, Its working to me

**Comment by sudesh-kumar-cse** [comment]
> Fixed in 19.3.1

Thank you for your quick response @rlepinski, Its working to me 👍

**Comment by JorenVos** [comment]
This issue started to occur again in the latest release.
